### ISSUE TITLE
Interview process is offset to the right

### ISSUE THREAD

**Issue by lukas-wg2** [omnicate/omnicate.github.io#48]
The interview steps are shifted to the right side of the page, and the left side is empty. This makes it kinda akward to read imo. I don't know how to try to fix this myself.
![Screenshot from 2021-06-23 17-01-57](https://user-images.githubusercontent.com/43165886/123120836-f0568a00-d444-11eb-9c26-2ece622a0ea7.png)

**Comment by david-wg2** [comment]
See https://github.com/omnicate/omnicate.github.io/issues/49#issuecomment-866966464 - write to me on Slack if you want the tl;dr.
