### ISSUE TITLE
Careers page image

### ISSUE THREAD

**Issue by lukas-wg2** [omnicate/omnicate.github.io#49]
We should have one of our own photos for the careers page. Having some random dude drawing diagrams of some sort of receipt system doesn't seem that telco related...
![image](https://user-images.githubusercontent.com/43165886/123121515-82f72900-d445-11eb-947b-88e0e992cb28.png)

**Comment by david-wg2** [comment]
Sadly, we don't control our own webpage anymore, so creating this issue won't help. I don't really want to get into any of that in this issue, but you can search on Slack to find out what's up.
